---
journalReviewer:
  - International Journal of Quantum Information
  - Quantum Machine Intelligence
  - npj Quantum Information
  - IEEE Transactions on Quantum Engineering

conferenceReviewer:
  - QTML 2023
  - TAMC 2024
  - TQC 2024
  - NeurIPS 2025
  - QIP 2026
  - ICLR 2026

conferencevolunteer:
  - SEEQA 2025
  - QCTiP 2026
