---
journal:
  - International Journal of Quantum Information
  - Quantum Machine Intelligence
  - npj Quantum Information
  - IEEE Transactions on Quantum Engineering

conference:
  - QTML 2023
  - TAMC 2024
  - TQC 2024
  - NeurIPS 2025
  - QIP 2026
  - ICLR 2026

volunteer:
  - SEEQA 2025
